/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 18
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_PLUS = 7,
  anon_sym_DASH = 8,
  anon_sym_STAR = 9,
  anon_sym_SLASH = 10,
  anon_sym_PERCENT = 11,
  anon_sym_SEMI = 12,
  sym_num_literal = 13,
  sym_identifier = 14,
  sym_source = 15,
  sym__definition = 16,
  sym_function_definition = 17,
  sym_block = 18,
  sym_statement = 19,
  sym_bin_op = 20,
  sym_assignment = 21,
  sym_binary_operator = 22,
  sym_lvalue = 23,
  sym_expr_statement = 24,
  sym_literal = 25,
  sym_expr = 26,
  aux_sym_source_repeat1 = 27,
  aux_sym_block_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_SEMI] = ";",
  [sym_num_literal] = "num_literal",
  [sym_identifier] = "identifier",
  [sym_source] = "source",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_bin_op] = "bin_op",
  [sym_assignment] = "assignment",
  [sym_binary_operator] = "binary_operator",
  [sym_lvalue] = "lvalue",
  [sym_expr_statement] = "expr_statement",
  [sym_literal] = "literal",
  [sym_expr] = "expr",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_num_literal] = sym_num_literal,
  [sym_identifier] = sym_identifier,
  [sym_source] = sym_source,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_bin_op] = sym_bin_op,
  [sym_assignment] = sym_assignment,
  [sym_binary_operator] = sym_binary_operator,
  [sym_lvalue] = sym_lvalue,
  [sym_expr_statement] = sym_expr_statement,
  [sym_literal] = sym_literal,
  [sym_expr] = sym_expr,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_op] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_lvalue] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_add = 1,
  field_assign = 2,
  field_body = 3,
  field_closing_bracket = 4,
  field_div = 5,
  field_expr = 6,
  field_fn = 7,
  field_left = 8,
  field_lvalue = 9,
  field_mod = 10,
  field_mul = 11,
  field_name = 12,
  field_opening_bracket = 13,
  field_operator = 14,
  field_right = 15,
  field_semicolon = 16,
  field_sub = 17,
  field_var = 18,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_add] = "add",
  [field_assign] = "assign",
  [field_body] = "body",
  [field_closing_bracket] = "closing_bracket",
  [field_div] = "div",
  [field_expr] = "expr",
  [field_fn] = "fn",
  [field_left] = "left",
  [field_lvalue] = "lvalue",
  [field_mod] = "mod",
  [field_mul] = "mul",
  [field_name] = "name",
  [field_opening_bracket] = "opening_bracket",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_semicolon] = "semicolon",
  [field_sub] = "sub",
  [field_var] = "var",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 1},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 3},
  [12] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 4},
    {field_fn, 0},
    {field_name, 1},
  [3] =
    {field_closing_bracket, 1},
    {field_opening_bracket, 0},
  [5] =
    {field_var, 0},
  [6] =
    {field_add, 0},
  [7] =
    {field_sub, 0},
  [8] =
    {field_mul, 0},
  [9] =
    {field_div, 0},
  [10] =
    {field_mod, 0},
  [11] =
    {field_expr, 0},
    {field_semicolon, 1},
  [13] =
    {field_closing_bracket, 2},
    {field_opening_bracket, 0},
  [15] =
    {field_assign, 1},
    {field_expr, 2},
    {field_lvalue, 0},
  [18] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 19,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 20,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '%') ADVANCE(23);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(19);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') SKIP(8);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(23);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(19);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == '=') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '*') SKIP(4);
      if (lookahead == '/') SKIP(7);
      END_STATE();
    case 3:
      if (lookahead == '*') SKIP(3);
      if (lookahead == '/') SKIP(5);
      if (lookahead != 0) SKIP(4);
      END_STATE();
    case 4:
      if (lookahead == '*') SKIP(3);
      if (lookahead != 0) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '/') SKIP(2);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(5);
      if (lookahead != 0) SKIP(7);
      END_STATE();
    case 8:
      if (eof) ADVANCE(12);
      if (lookahead == '*') SKIP(10);
      if (lookahead == '/') SKIP(11);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      if (lookahead == '*') SKIP(9);
      if (lookahead == '/') SKIP(0);
      if (lookahead != 0) SKIP(10);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '*') SKIP(9);
      if (lookahead != 0) SKIP(10);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(0);
      if (lookahead != 0) SKIP(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_num_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_num_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(32),
    [sym__definition] = STATE(16),
    [sym_function_definition] = STATE(16),
    [aux_sym_source_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(10), 1,
      anon_sym_RBRACE,
    ACTIONS(12), 1,
      sym_num_literal,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(8), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(17), 2,
      sym_block,
      sym_expr_statement,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [32] = 9,
    ACTIONS(18), 1,
      anon_sym_LBRACE,
    ACTIONS(20), 1,
      anon_sym_RBRACE,
    ACTIONS(22), 1,
      sym_num_literal,
    ACTIONS(24), 1,
      sym_identifier,
    STATE(8), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(4), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(17), 2,
      sym_block,
      sym_expr_statement,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [64] = 9,
    ACTIONS(18), 1,
      anon_sym_LBRACE,
    ACTIONS(22), 1,
      sym_num_literal,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(26), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(17), 2,
      sym_block,
      sym_expr_statement,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [96] = 9,
    ACTIONS(18), 1,
      anon_sym_LBRACE,
    ACTIONS(22), 1,
      sym_num_literal,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(17), 2,
      sym_block,
      sym_expr_statement,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [128] = 9,
    ACTIONS(18), 1,
      anon_sym_LBRACE,
    ACTIONS(22), 1,
      sym_num_literal,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(17), 2,
      sym_block,
      sym_expr_statement,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [160] = 3,
    ACTIONS(32), 1,
      anon_sym_EQ,
    ACTIONS(36), 1,
      anon_sym_SLASH,
    ACTIONS(34), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SEMI,
  [174] = 7,
    ACTIONS(38), 1,
      anon_sym_PLUS,
    ACTIONS(40), 1,
      anon_sym_DASH,
    ACTIONS(42), 1,
      anon_sym_STAR,
    ACTIONS(44), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      anon_sym_PERCENT,
    ACTIONS(48), 1,
      anon_sym_SEMI,
    STATE(11), 1,
      sym_binary_operator,
  [196] = 5,
    ACTIONS(22), 1,
      sym_num_literal,
    ACTIONS(24), 1,
      sym_identifier,
    STATE(10), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [214] = 7,
    ACTIONS(38), 1,
      anon_sym_PLUS,
    ACTIONS(40), 1,
      anon_sym_DASH,
    ACTIONS(42), 1,
      anon_sym_STAR,
    ACTIONS(44), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      anon_sym_PERCENT,
    ACTIONS(50), 1,
      anon_sym_SEMI,
    STATE(11), 1,
      sym_binary_operator,
  [236] = 5,
    ACTIONS(22), 1,
      sym_num_literal,
    ACTIONS(24), 1,
      sym_identifier,
    STATE(12), 1,
      sym_expr,
    STATE(33), 1,
      sym_lvalue,
    STATE(14), 3,
      sym_bin_op,
      sym_assignment,
      sym_literal,
  [254] = 3,
    ACTIONS(54), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      sym_binary_operator,
    ACTIONS(52), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SEMI,
  [268] = 2,
    ACTIONS(58), 1,
      anon_sym_SLASH,
    ACTIONS(56), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SEMI,
  [279] = 2,
    ACTIONS(36), 1,
      anon_sym_SLASH,
    ACTIONS(34), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SEMI,
  [290] = 3,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_fn,
    STATE(15), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_repeat1,
  [302] = 3,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    STATE(15), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_repeat1,
  [314] = 1,
    ACTIONS(67), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
      sym_identifier,
  [321] = 1,
    ACTIONS(69), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
      sym_identifier,
  [328] = 1,
    ACTIONS(71), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
      sym_identifier,
  [335] = 1,
    ACTIONS(73), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
      sym_identifier,
  [342] = 2,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_block,
  [349] = 1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [354] = 1,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [359] = 1,
    ACTIONS(79), 2,
      sym_num_literal,
      sym_identifier,
  [364] = 1,
    ACTIONS(81), 2,
      sym_num_literal,
      sym_identifier,
  [369] = 1,
    ACTIONS(83), 2,
      sym_num_literal,
      sym_identifier,
  [374] = 1,
    ACTIONS(85), 2,
      sym_num_literal,
      sym_identifier,
  [379] = 1,
    ACTIONS(87), 2,
      sym_num_literal,
      sym_identifier,
  [384] = 1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [389] = 1,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
  [393] = 1,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
  [397] = 1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [401] = 1,
    ACTIONS(95), 1,
      anon_sym_EQ,
  [405] = 1,
    ACTIONS(97), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 214,
  [SMALL_STATE(11)] = 236,
  [SMALL_STATE(12)] = 254,
  [SMALL_STATE(13)] = 268,
  [SMALL_STATE(14)] = 279,
  [SMALL_STATE(15)] = 290,
  [SMALL_STATE(16)] = 302,
  [SMALL_STATE(17)] = 314,
  [SMALL_STATE(18)] = 321,
  [SMALL_STATE(19)] = 328,
  [SMALL_STATE(20)] = 335,
  [SMALL_STATE(21)] = 342,
  [SMALL_STATE(22)] = 349,
  [SMALL_STATE(23)] = 354,
  [SMALL_STATE(24)] = 359,
  [SMALL_STATE(25)] = 364,
  [SMALL_STATE(26)] = 369,
  [SMALL_STATE(27)] = 374,
  [SMALL_STATE(28)] = 379,
  [SMALL_STATE(29)] = 384,
  [SMALL_STATE(30)] = 389,
  [SMALL_STATE(31)] = 393,
  [SMALL_STATE(32)] = 397,
  [SMALL_STATE(33)] = 401,
  [SMALL_STATE(34)] = 405,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [7] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [10] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [12] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lvalue, 1, 0, 3),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 11),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bin_op, 3, 0, 12),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_op, 3, 0, 12),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_statement, 2, 0, 9),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 10),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 7),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 5),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 6),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 4),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 8),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_yap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "yap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
